.catalog:
  name: spark
  version: "v2.0.2-rancher1"
  description: "Apache Spark"
  minimum_rancher_version: v1.0.0
  questions:
    - variable: "SSHUSER"
      label: "SSH user name"
      description: "supply ssh user name (default is spark)"
      type: "string"
      default: "spark"
      required: false
sparkdriver:
  scale: 1
  start_on_create: true
