.catalog:
  name: Frontend-CentOS7
  version: "v7.3.1-rancher1"
  description: "CentOS7 for interactive frontend"
  minimum_rancher_version: v1.0.0
  questions:
    - variable: "SSHUSER"
      label: "SSH user name"
      description: "supply ssh user name (default is root)"
      type: "string"
      default: "root"
      required: false
frontend-centos7:
  scale: 1
  start_on_create: true
