.catalog:
  name: Cassndra
  version: "v3.9.0-rancher1"
  description: "Apache Cassandra"
  minimum_rancher_version: v1.0.0
  questions:
    - variable: "NODE_COUNT"
      label: "NODE_COUNT"
      description: "Number of Cassandra nodes(excl. master)"
      type: "int"
      default: "2"
      required: true
    - variable: "SSHUSER"
      label: "SSH user name"
      description: "supply ssh user name (default is cassandra)"
      type: "string"
      default: "cassandra"
      required: true
seed:
  scale: 1
  start_on_create: true
node:
  scale: ${NODE_COUNT}
  start_on_create: true
