.catalog:
  name: kafka
  version: "v0.10.2-rancher1"
  description: "Apache Kafka"
  minimum_rancher_version: v1.0.0
  questions:
    - variable: "NODE_COUNT"
      label: "NODE_COUNT"
      description: "Number of Kafka brokers"
      type: "int"
      default: "3"
      required: true
    - variable: "SSHUSER"
      label: "SSH user name"
      description: "supply ssh user name (default is kafka)"
      type: "string"
      default: "kafka"
      required: false
kafka:
  scale: ${NODE_COUNT}
  start_on_create: true
